---
abstract: 'yet another assertion keyword'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::Modern: 0.007
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 1
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlX-Assert
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  PerlX::Assert:
    file: lib/PerlX/Assert.pm
    version: 0.900_00
  PerlX::Assert::DD:
    file: lib/PerlX/Assert/DD.pm
    version: 0.900_00
  PerlX::Assert::Keyword:
    file: lib/PerlX/Assert/Keyword.pm
    version: 0.900_00
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/PerlX-Assert/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=PerlX-Assert
  homepage: https://metacpan.org/release/PerlX-Assert
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-perlx-assert.git
version: 0.900_00
